strv="Yashodhan"
ite=iter(strv)
print(ite.__next__())#Y
print(ite.__next__())#a
print(ite.__next__())#s
print(ite.__next__())#h
print(ite.__next__())#o
print(ite.__next__())#d
print(ite.__next__())#h
print(ite.__next__())#a
print(ite.__next__())#n